FROM mcr.microsoft.com/devcontainers/base:focal
LABEL org.opencontainers.image.source=https://github.com/EvilJoker/product_imagemagic
ARG DEBIAN_FRONTEND=noninteractive

COPY config/sources.list /etc/apt/sources.list
COPY config/pip.conf /root/.pip/pip.conf